set encoding=utf-8
set expandtab
set tabstop=4
set shiftwidth=4
set hlsearch
syntax on

set nocompatible               " be iMproved  
filetype off                   " required!  
  
set rtp+=~/.vim/bundle/vundle/  
call vundle#rc()  
  
" let Vundle manage Vundle  
" required!   
"这是vundle本身的设置  
Bundle 'gmarik/vundle'    
   
" My Bundles here:  
"这里是设置你自己自定义的插件的设置vundle设置，注意：下载的插件git为：https://github.com/godlygeek/tabular.git，则设置为Bundle 'godlygeek/tabular';https://github.com/gmarik/vundle.git设置则为 Bundle 'gmarik/vundle'    
" original repos on github  
"Bundle 'godlygeek/tabular'  
Bundle 'SuperTab'  

" vim-scripts repos，vim-scripts的访问地址，格式则如下：  
"Bundle 'L9'  
"Bundle 'FuzzyFinder'  
" non github repos ，非git的访问地址的，格式如下：  
"Bundle 'git://git.wincent.com/command-t.git'  
" ...  
  
filetype plugin indent on     " required!  
"  
" Brief help  
" :BundleList          - list configured bundles  
" :BundleInstall(!)    - install(update) bundles  
" :BundleSearch(!) foo - search(or refresh cache first) for foo  
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles  
"  
" see :h vundle for more details or wiki for FAQ  
" NOTE: comments after Bundle command are not allowed.. 

"For pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on

"For ctags
let Tlist_Ctags_Cmd='/usr/local/bin/ctags'

"Set the status line options. Make it show more information.
set laststatus=2
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}
"Set Color Scheme and Font Options
colorscheme molokai
set guifont=Consolas:h18
"set line no, buffer, search, highlight, autoindent and more.
set nu
set hidden
set ignorecase
set incsearch
set smartcase
set showmatch
set autoindent
set ruler
set vb
set viminfo+=n$VIM/_viminfo
set noerrorbells
set showcmd
set mouse=a
set history=1000
set undolevels=1000

"For NERDtree
autocmd vimenter * NERDTree
map <C-n> :NERDTreeToggle<CR>

